# Generated by Django 4.2.21 on 2025-05-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_current_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='김준홍', max_length=50),
        ),
    ]
