# Generated by Django 4.2.21 on 2025-05-22 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_total_pages_read_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_food',
            field=models.IntegerField(default=0),
        ),
    ]
