# Generated by Django 4.2.21 on 2025-05-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kkubook", "0005_book_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingrecord",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kkubook.book",
            ),
            preserve_default=False,
        ),
    ]
