# Generated by Django 4.2.21 on 2025-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kkubook", "0006_readingrecord_book"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="readingrecord",
            name="unique_user_date",
        ),
        migrations.AddConstraint(
            model_name="readingrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "book", "created_at"), name="unique_user_book_date"
            ),
        ),
    ]
