# Generated by Django 4.2.21 on 2025-05-25 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kkubook", "0008_remove_readingrecord_unique_user_book_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readingrecord_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
