# Generated by Django 4.2.21 on 2025-05-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkubook', '0010_readingrecord_is_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='gpt_generated',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkubook.book'),
        ),
    ]
