# Generated by Django 4.2.21 on 2025-05-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkubook', '0011_rename_correct_answer_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrecord',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
