# Generated by Django 4.2.21 on 2025-05-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkubook', '0013_book_description_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
